//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Sale_Permit_FK { get; set; }
        public int Supply_Permit_FK { get; set; }
        public int Qty { get; set; }
        public int Product_FK { get; set; }
        public System.DateTime ProDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sale_Permit Sale_Permit { get; set; }
        public virtual Supply_Permit Supply_Permit { get; set; }
    }
}
